name: Build Docker Image

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: "The name and tag of the Docker image to build"
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ inputs.image-tag }} .