name: 02 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js 14
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar las pruebas
      - name: Run tests
        run: npm test

      # Subir resultados de pruebas como artefacto
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: test-results
