name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  dast:
    needs: [build, docker]
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}

  deploy:
    name: Deploy to GitHub Pages
    needs: dast
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ajusta la versión de Node.js si es necesario

      - name: Install dependencies
        run: |
          npm install  # O usa `yarn install` si es lo que utilizas

      - name: Build the project
        run: |
          npm run build  # Asegúrate de que tu script de build esté correctamente configurado

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Puedes usar 'main' si prefieres desplegar en la rama principal
          folder: build # Asegúrate de que esta carpeta esté configurada correctamente para tu construcción, como 'dist' o 'public'

      - name: Clean up
        run: echo "Cleanup complete"
