name: SCA with SonarCloud

on:
  workflow_dispatch:
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  sca:
    name: SCA Node.js Project with SonarCloud
    runs-on: ubuntu-20.04

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js 14
      - name: Set up Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Instalar SonarCloud Scanner
      - name: Install SonarCloud Scanner
        run: npm install -g sonarqube-scanner

      # Ejecutar análisis con SonarCloud
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=kbgr55 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      # Subir artefactos del análisis de SonarCloud
      - name: Upload SonarCloud Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sonarcloud-report
          path: .scannerwork